Issue/webpack 5 upgrade
ucfopen/Materia-Widget-Dev-Kit pull request #106
Opened 2023-05-25 21:58 UTC by cayb0rg

## Requirements: 
- Node v16 or later (including v18)

## Local setup
### Materia
The current Materia widget-dependencies-package does not support the MWDK.
1. Checkout this [issue/widget-dependencies-package-part-three branch](https://github.com/cayb0rg/Materia/tree/react/widget-dependencies-package-part-three) of Materia. This is required to load the player and creator.
2. Run ``yarn build`` inside the Materia folder. 
3. Run ``yarn link`` inside Materia's /public/dist folder.
4. Start Materia (run ``docker-compose up`` and ``yarn dev``)

### Widget
Each widget may need a few small changes to support Webpack v5. Here is an incomprehensive list of the possible changes:

1. New webpack.config.js entry rules:
- Include only entries that have HTML (or markdown) files, as these will be used by HtmlWebpackPlugin. Include the HTML file as the first element, then include any necessary JS and CSS in the array.
- There should be no extension in the entry's name.
- CSS should not be their own entries

It should look similar to:
![image](https://github.com/ucfopen/Materia-Widget-Dev-Kit/assets/46247315/ee5ea569-68b5-4b06-8dad-90cd1a127c0f)

2. Either include CSS inside your JS files for MiniCssExtractPlugin to recognize them, or include them as elements in the entry file (see above).
3. Update the NPM scripts inside ``package.json`` to:
```
"start": "mwdk-start",
"build": "mwdk-build-prod",
"build-dev": "mwdk-build-dev"
```

Look at an [example](https://github.com/cayb0rg/syntax-sorter-materia-widget/commit/d14839dc30d46c2c89c0cf7120abc40f25ce4cad) for the changes that need to be made (ignore the icon resizing).

### Running MWDK
1. Run ``yarn link materia-widget-dependencies`` inside the Materia Widget Development Kit
2. Run ``yarn build`` inside the Materia Widget Development Kit.
3. Run ``yarn link`` inside the Materia Widget Development Kit.
4. Run ``yarn remove materia-widget-development-kit`` inside your widget.
5. Run ``yarn link materia-widget-development-kit`` inside your widget.
6. Run ``yarn install`` inside your widget.
7. Run ``yarn start`` inside your widget.

## Known Bugs
- Angular widgets do not work.
- Not updating the title of a widget may cause an error when trying to preview it.
- Question importer does not work.

2023-10-09 19:55 UTC, clpetersonucf requested changes
Really great work here so far. With limited issues I was able to get one of your widget PRs running locally and installed to dev Materia.

Some high-level comments:

- As commented, MWD has been updated to hopefully (?) include the most recent/missing dependencies. It's worth confirming 0.2.0 works out of the box, and replace the reference to it in the package.json when possible.
- I _love_ the little progress bar when installing to local Materia. That's a nice touch.
- I haven't tested the score screen feature, but the instructions could be a little clearer as to what's required. If the score screen options aren't ready for prime-time, we could also potentially disable them until they have more time in the oven.
- Previously the MWDK would allow you to save draft/publish a qset to test in the player. Right now it looks like the demo is the only qset that works with the player. Is that the case? Are there significant challenges to re-implementing cached qsets?
- Would it be possible to render Player and Creator guides, if they exist, within the MWDK? It looks like we already have view templates to support them.

Otherwise, just a little bit of polish based on feedback items, and making sure all current changes on this branch are final, required, and complete, and it looks like it might be good to go.

2023-10-09 19:55 UTC, clpetersonucf commented on qsets/.gitkeep
At least as of right now, `yarn start` initializes but the webpack dev server errors out as soon as you load `localhost:8118` because the `qsets/` dir is missing.

2023-10-09 19:55 UTC, clpetersonucf commented on express.js
> +	let targetImage = execSync('docker ps -a --format "{{.Image}} {{.Names}}" | grep -e ".*materia:.* docker_app_.*" | head -n 1 | cut -d" " -f2');
This line continues to give us problems. Some versions of docker-compose use hyphens, others use underscores, and the server does not handle a search failure well. We can modify the search pattern grep is using to: `".*materia:.* docker[-_]app[-_].*"` which will catch either option.

2023-10-09 19:55 UTC, clpetersonucf commented on .vscode/settings.json
Is this file (and corresponding directory) required?

2023-10-09 19:55 UTC, clpetersonucf commented on package.json
> +    "materia-widget-dependencies": "0.0.5",
MWD is now at `0.2.0` and should include the missing `path.js` file.

2023-10-09 19:55 UTC, clpetersonucf commented on webpack-widget.js
> +			// flatten: true,
Required?

2023-10-09 19:56 UTC, clpetersonucf commented on express.js
> +	let targetImage = execSync('docker ps -a --format "{{.Image}} {{.Names}}" | grep -e ".*materia:.* docker_app_.*" | head -n 1 | cut -d" " -f2');
Also it'd be nice if the server gave a more well-handled response if the docker install process runs into an issue

2023-10-10 20:08 UTC, cayb0rg commented
Thanks for the feedback! 

New changes:
- Updated materia-widget-dependencies package version to 0.2.0
- Fixed link to `guides.js` in guide pages
- Updated scorescreen instructions
- The kit should support `demo` and one additional instance. I've added the ability to have multiple widget instances.
- Made the widget installation process more verbose so that all errors are forwarded to the user as they are received

2023-10-20 19:28 UTC, clpetersonucf approved these changes
There might be some edge case issues we haven't encountered yet, but nothing show-stopping. By all accounts the new dev kit does the job required and works great.

Really excellent work. This was a significant undertaking and you knocked it out of the park.

2023-10-24 15:51 UTC, FrenjaminBanklin approved these changes
Super minor nitpick with some inline spacing, but nothing I'd hold up a release for.

I couldn't get the score screen working with valid JSON, but considering the latest version of the MWDK doesn't have a functional score screen either I'm not sure I'd hold up a release for that, either.

Everything looks like it's working well otherwise.

2023-10-24 15:51 UTC, FrenjaminBanklin commented on express.js
> +const webpackDevMiddleware 	= require('webpack-dev-middleware');
This doesn't really matter, but stick to spaces for inline alignment.

Would prefer to remove all the extraneous white space, personally.

2023-10-24 17:13 UTC, merged