Qset standardization + various smaller patches
ucfopen/Materia-Widget-Dev-Kit pull request #124
Opened 2024-10-02 19:13 UTC by fudgeu

**This PR is built off of dev/3.0.3 and requires that to be merged in first**

This PR includes a few fixes and patches for various things:
- Fixed #120 - Qsets are now 'standardized' the same way that Materia Docker would standardize them. Much of the code for this standardization is heavily based off Materia Docker's code, so the behavior should be identical. Fields that are outside of what is expected in certain places (like 'options' within a question object, the issue I had) are now stripped and reported about in the console.
  - The other preflight issues linked in 120 are not resolved by this PR, but some of them should be pretty easy to implement now given some of the functions this PR provides. I can work on them either as additions to this PR or a separate one.
- Alert dialogs now show up again. Previously, a custom CSS rule was put in place to prevent a login timeout alert from showing up. This however prevents any alert dialog from showing up, including those sent by the widget when attempting to save. With the custom CSS removed, I don't seem to be getting any login timeouts anyway (but maybe some more testing/poking around is needed).
- MWDK now checks for the presence of either `webpack.config.js` _or_ `webpack.config.cjs` when initializing. This allows the easy use of an explicitly-defined CommonJS webpack config, saving some headaches when your project is using `"type": "module"` (like Pyramid Game is)

2024-12-17 20:04 UTC, clpetersonucf requested changes
Works great aside from a few missing references that were hard-coded to the layout handlebar file. One other thing I've noticed: the score screen is an optional addition to the `install.yaml`, and the preflight check should indicate that.

If the score screen property is present in `install.yaml`, we should probably verify the file referenced actually exists. Potentially conversely, if a score screen html file is present, it should probably check that the property is in the `install.yaml`.

2025-01-06 19:42 UTC, fudgeu commented on views/layout.hbs
> +		<script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.9/angular.min.js"></script>
Doesn't seem to be required for MWDK to work, so I've removed them.

On that note, it seems like other AngularJS references exist in other files already (like `creator_mwdk.hbs`), so it might be worth a look to see if those are necessary as well.

2025-01-06 19:42 UTC, fudgeu commented on views/layout.hbs
> +		<script src="/mdk/assets/js/materia.js"></script>
Removed! Looks like they were ancient artifacts from 5 years ago.

2025-01-06 19:43 UTC, fudgeu commented on views/layout.hbs
> +		<script src="/mdk/mdk-assets/js/mdk-package.js"></script>
^ Same as above

2025-02-04 17:33 UTC, merged